

# VAR1 = helloworld
VAR1 = oop1
# VAR1 = oop2
# VAR1 = oop3
# VAR1 = oop4
# VAR1 = oop5


VAR2 = binaryoutput



love: $(VAR1).cpp
	# g++ $(VAR1).cpp -o ./binOutput/$(VAR2)
	g++ $(VAR1).cpp -o ./$(VAR2)
	# sleep 1
	# echo "hello world! hahaha!"
	# sleep 1
	clear
	# ./binOutput/$(VAR2)
	./$(VAR2)

clear:
	rm ./binOutput/$(VAR2)